// ═══════════════════════════════════════════════════════
//  Fish Cinema — Общая база фильмов
//  Подключи этот файл на любой странице фильма:
//  <script src="movies_data.js"></script>
//  Затем вызови: renderSmartRecs("movieKey", "rec-grid-id")
// ═══════════════════════════════════════════════════════

const FISH_MOVIES = [
  { title:"Зелёная книга",                   file:"Green_book.html",                            key:"Green Book",                            year:2018, country:"США",             genres:["драма","биография"],           directors:["Питер Фаррелли"],                    actors:["Вигго Мортенсен","Махершала Али"],                                       img:"https://new.kinogo.fi/poster/100/1108577.jpg" },
  { title:"Первый мститель",                 file:"Captain_america.html",                       key:"Captain America The First Avenger",     year:2011, country:"США",             genres:["боевик","фантастика"],         directors:["Джо Джонстон"],                      actors:["Крис Эванс","Томми Ли Джонс","Хьюго Уивинг"],                           img:"https://kinogo.online/uploads/posts/2021-02/1614451243-2137657427.jpg" },
  { title:"Элизиум: Рай не на Земле",        file:"Elysium.html",                               key:"Elysium",                               year:2013, country:"США",             genres:["фантастика","боевик"],         directors:["Нилл Бломкамп"],                     actors:["Мэтт Дэймон","Джоди Фостер","Шарлто Копли"],                            img:"https://svit.tartugi.net/uploads/posts/2024-02/1707064518-elizium-ray-ne-na-zemle.jpg" },
  { title:"Я, снова я и Ирэн",               file:"Me_myself_irene_2.html",                     key:"Me Myself and Irene",                   year:2000, country:"США",             genres:["комедия"],                     directors:["Питер Фаррелли","Бобби Фаррелли"],   actors:["Джим Керри","Рене Зеллвегер"],                                          img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgaGCcpsdKcQLyjRLWW9ZOGmQOU9JyuLV2zQ&s" },
  { title:"Тупой и ещё тупее",               file:"Dumb_and_dumber.html",                       key:"Dumb and Dumber To",                    year:2014, country:"США",             genres:["комедия"],                     directors:["Питер Фаррелли","Бобби Фаррелли"],   actors:["Джим Керри","Джефф Дэниелс"],                                           img:"https://ikinogo.biz/uploads/mini/fullsm/2d/7a4245fcc4d7bacc66bb7ff25f32f1.jpg" },
  { title:"Звёздный путь",                   file:"Star_trek.html",                             key:"Star Trek 2009",                        year:2009, country:"США",             genres:["фантастика","боевик"],         directors:["Дж.Дж. Абрамс"],                     actors:["Крис Пайн","Закари Куинто","Карл Урбан"],                               img:"https://upload.wikimedia.org/wikipedia/ru/2/29/Startrekposter.jpg" },
  { title:"Хороший, Плохой, Злой",           file:"good-bad-ugly.html",                         key:"good-bad-ugly",                         year:1966, country:"Испания",         genres:["вестерн"],                     directors:["Серджо Леоне"],                      actors:["Клинт Иствуд","Эли Уоллак","Ли Ван Клиф"],                             img:"https://kinogo.online/uploads/mini/shortstory-mob/ed1/1614517323-1826304193.jpg" },
  { title:"Бойцовский клуб",                 file:"fight_club.html",                            key:"Fight Club",                            year:1999, country:"США",             genres:["триллер","драма"],             directors:["Дэвид Финчер"],                      actors:["Брэд Питт","Эдвард Нортон","Хелена Бонэм Картер"],                     img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHFS7WEw3dSnvD-pu6GKh0CDhf5g6uXC6vow&s" },
  { title:"Таксист",                         file:"taxi_driver_1976.html",                      key:"taxi_driver_1976",                      year:1976, country:"США",             genres:["драма","триллер"],             directors:["Мартин Скорсезе"],                   actors:["Роберт Де Ниро","Джоди Фостер","Харви Кейтель"],                        img:"https://preview.redd.it/taxi-driver-1976-v0-2vafsern2tnf1.jpg?width=640&crop=smart&auto=webp&s=c0319ef604e7680dd8c420851d775d7fe9d2f549" },
  { title:"За пригоршню долларов",           file:"per_un_pugno_di_dollari.html",               key:"Per un pugno di dollari",               year:1964, country:"Италия",          genres:["вестерн"],                     directors:["Серджо Леоне"],                      actors:["Клинт Иствуд","Джан Мария Волонте"],                                    img:"https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/1c264e88-1b05-4df3-8bb4-8d6316e9270d/600x900" },
  { title:"На несколько долларов больше",    file:"for-a-few-dollars-more.html",                key:"For a Few Dollars More",                year:1965, country:"Испания",         genres:["вестерн"],                     directors:["Серджо Леоне"],                      actors:["Клинт Иствуд","Ли Ван Клиф","Джан Мария Волонте"],                     img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCxtEljwymUbifbP48s0ryFIgLy1OYI-j4mQ&s" },
  { title:"Хулиганы Зеленой улицы",         file:"Green_Street_hooligans.html",                key:"Green_Street_hooligans",                year:2005, country:"Великобритания",  genres:["драма","боевик"],              directors:["Лекси Александр"],                  actors:["Элайджа Вуд","Чарли Ханнэм"],                                           img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxHJV4wLnEGE55pI8bIKVStLfKanT8O9gYXQ&s" },
  { title:"Великий уравнитель",              file:"The_Equalizer.html",                         key:"The Equalizer",                         year:2014, country:"США",             genres:["боевик","триллер"],            directors:["Антуан Фукуа"],                      actors:["Дензел Вашингтон","Хлоя Морец"],                                        img:"https://avatars.mds.yandex.net/get-kinopoisk-image/1946459/f0031dfe-adf2-4b26-a5e2-7dfc404a2124/220x330" },
  { title:"Старикам тут не место",           file:"No_Country_for_Old_Men.html",                key:"No Country for Old Men",                year:2007, country:"США",             genres:["триллер","криминал","драма"],  directors:["Итан Коэн","Джоэл Коэн"],            actors:["Хавьер Бардем","Томми Ли Джонс","Джош Бролин"],                        img:"https://kinogo.online/uploads/posts/2021-02/1614528496-1821078516.jpg" },
  { title:"Гарольд и Кумар уходят в отрыв", file:"Harold_&_Kumar_Go_to_White_Castle.html",     key:"Harold & Kumar Go to White Castle",     year:2004, country:"США",             genres:["комедия"],                     directors:["Денни Лейнер"],                      actors:["Джон Чо","Кал Пенн"],                                                   img:"https://upload.wikimedia.org/wikipedia/ru/9/9f/Harold_%26_Kumar_Go_to_White_Castle.jpg" },
  { title:"Скауты против зомби",            file:"Scouts_Guide_to_the_Zombie_Apocalypse.html", key:"Scouts Guide to the Zombie Apocalypse", year:2015, country:"США",             genres:["комедия","ужасы"],             directors:["Кристофер Ландон"],                  actors:["Тай Шеридан","Логан Миллер"],                                           img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNnvbVtGJ_vWshr3Rlh7_FVI0gUw2-lovnZg&s" },
  { title:"Поезд в Пусан",                  file:"Busanhaeng.html",                            key:"Busanhaeng",                            year:2016, country:"Южная Корея",     genres:["ужасы","боевик","драма"],      directors:["Ён Сан-хо"],                         actors:["Кон Ю","Чон Ю-ми","Ма Дон-сок"],                                       img:"https://thumbs.dfs.ivi.ru/storage0/contents/7/8/4b95783a0147f383c9f0b0bb1bc691.jpg" },
  { title:"Добро пожаловать в Зомбилэнд",   file:"Zombieland.html",                            key:"Zombieland",                            year:2009, country:"США",             genres:["комедия","ужасы"],             directors:["Рубен Фляйшер"],                     actors:["Джесси Айзенберг","Вуди Харрельсон","Эмма Стоун"],                     img:"https://kinogo.online/uploads/posts/2021-02/1614519780-1944811101.jpg" },
  { title:"Отряд самоубийц",                file:"Suicide_squad.html",                         key:"Suicide Squad",                         year:2016, country:"США",             genres:["боевик","фантастика"],         directors:["Дэвид Эйер"],                        actors:["Уилл Смит","Марго Робби","Джаред Лето"],                                img:"https://upload.wikimedia.org/wikipedia/ru/4/4d/Suicide_Squad.jpeg" },
  { title:"Хан Соло",                       file:"Solo_star_wars.html",                        key:"Solo A Star Wars Story",                year:2018, country:"США",             genres:["фантастика","боевик"],         directors:["Рон Ховард"],                        actors:["Олден Эренрайк","Эмилия Кларк","Дональд Гловер"],                      img:"https://kinogo.media/uploads/posts/2021-10/1634804136_iphone360_841277.jpg" },
  { title:"Плохие парни",                   file:"Bad_boys.html",                              key:"Bad Boys",                              year:1995, country:"США",             genres:["боевик","комедия"],            directors:["Майкл Бэй"],                         actors:["Уилл Смит","Мартин Лоуренс"],                                           img:"https://play-lh.googleusercontent.com/JZn-yp1_a7RD8Wwk9-CgL-B-Fa51RaGt8rNITKLFddwYhtCLQ1fKd9MlY1OegXRkx1HS" },
  { title:"Троя",                           file:"Troy.html",                                  key:"Troy",                                  year:2004, country:"США",             genres:["боевик","история","драма"],    directors:["Вольфганг Петерсен"],                actors:["Брэд Питт","Эрик Бана","Орландо Блум"],                                 img:"https://static.okko.tv/images/v4/61956c39-2775-427d-9a86-c43f1d8ce0e1" },
  { title:"Блэйд",                          file:"Blade.html",                                 key:"Blade",                                 year:1998, country:"США",             genres:["боевик","ужасы","фантастика"], directors:["Стивен Норрингтон"],                 actors:["Уэсли Снайпс","Стивен Дорф"],                                           img:"https://upload.wikimedia.org/wikipedia/ru/e/e5/Blade_2_plakat_gross.jpg" },
  { title:"Голодные игры",                  file:"Hunger_games.html",                          key:"The Hunger Games",                      year:2012, country:"США",             genres:["фантастика","боевик","драма"], directors:["Гэри Росс"],                         actors:["Дженнифер Лоуренс","Джош Хатчерсон","Лиам Хемсворт"],                  img:"https://kinogo.online/uploads/mini/shortstory-mob/84f/1614468212-1246767137.jpg" },
  { title:"Пункт назначения",               file:"Final_destination.html",                     key:"Final Destination",                     year:2000, country:"США",             genres:["ужасы","триллер"],             directors:["Джеймс Вонг"],                       actors:["Девон Сава","Али Ларте"],                                               img:"https://kinogo.online/uploads/posts/2021-02/1614472317-1321259434.jpg" },
  { title:"Полтора шпиона",                 file:"Spies.html",                                 key:"Spies 2015",                            year:2015, country:"США",             genres:["комедия","боевик"],            directors:["Пол Фейг"],                          actors:["Мелисса МакКарти","Джейсон Стэйтем","Джуд Лоу"],                       img:"https://www.palladium-cinema.com.ua/storage/upload/film/poltora-shpiona/spp-1.jpg" },
  { title:"Полицейская академия",           file:"Police_academy.html",                        key:"Police Academy 1984",                   year:1984, country:"США",             genres:["комедия"],                     directors:["Хью Уилсон"],                        actors:["Стив Гуттенберг","Ким Кэтролл"],                                        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvEIwhv3Ckww8VTUJpnjBaYVSC6YcVJl0Lhg&s" },
  { title:"Очень страшное кино",            file:"Scary_movie.html",                           key:"Scary Movie 2000",                      year:2000, country:"США",             genres:["комедия","пародия"],           directors:["Киинан Айвори Уэйанс"],              actors:["Шон Уэйанс","Марлон Уэйанс","Анна Фэрис"],                             img:"https://kinogo.online/uploads/posts/2021-02/1614431711-60734677.jpg" },
  { title:"Майор Пейн",                     file:"Major_payne.html",                           key:"Major Payne 1995",                      year:1995, country:"США",             genres:["комедия"],                     directors:["Ник Касл"],                          actors:["Дэймон Уэйанс"],                                                        img:"https://kinogo.online/uploads/mini/shortstory-mob/81e/1614363946-1621052681.jpg" },
  { title:"Без чувств",                     file:"Bez_chuvstv_1998.html",                      key:"Bez chuvstv 1998",                      year:1998, country:"Украина",         genres:["драма"],                       directors:["Николай Мащенко"],                   actors:["Богдан Ступка","Ада Роговцева"],                                        img:"https://mobb.kinovasek.men/uploads/posts/2025-03/67dafbd41d177.webp" },
  { title:"Робот по имени Чаппи",           file:"Chappie.html",                               key:"Chappie 2015",                          year:2015, country:"ЮАР / США",      genres:["фантастика","боевик"],         directors:["Нилл Бломкамп"],                     actors:["Дев Патель","Хью Джекман","Шарлто Копли"],                              img:"https://www.hdclub.ua/files/film_release/big/bigi55759efdc9425.jpg" },
  { title:"Рокки",                          file:"Rocky.html",                                 key:"Rocky 1976",                            year:1976, country:"США",             genres:["драма","спорт"],               directors:["Джон Эвилдсен"],                     actors:["Сильвестр Сталлоне","Тэлия Шайр","Берт Янг"],                          img:"https://kinogo.online/uploads/posts/2021-02/1614398240-303155765.jpg" },
  { title:"Да здравствует Франция!",        file:"Vive_la_France.html",                        key:"Vive la France 2013",                   year:2013, country:"Франция",         genres:["комедия"],                     directors:["Мурад Мустафа Борхани"],             actors:["Жозе Гарсия","Мед Хондо"],                                             img:"https://play-lh.googleusercontent.com/whxZ9r9DvZKBef7_ZorHAtbD5MINTF9xVk_pTcOvhwVCRYMfnOszsqAAoKkb4fvnON8aag" },
  { title:"Джентльмены",                    file:"Gentlemen.html",                             key:"The Gentlemen 2019",                    year:2019, country:"Великобритания",  genres:["криминал","комедия"],          directors:["Гай Ричи"],                          actors:["Мэттью МакКонахи","Чарли Ханнэм","Хью Грант","Колин Фаррелл"],         img:"https://new.kinogo.fi/poster/100/1143242.jpg" },
  { title:"Форрест Гамп",                   file:"Forrest_gump.html",                          key:"Forrest Gump 1994",                     year:1994, country:"США",             genres:["драма","мелодрама"],           directors:["Роберт Земекис"],                    actors:["Том Хэнкс","Робин Райт","Гэри Синис"],                                 img:"https://kinogo.online/uploads/posts/2021-02/1614404652-1341878282.jpg" },
  { title:"Рэмбо",                          file:"Rambo.html",                                 key:"Rambo First Blood 1982",                year:1982, country:"США",             genres:["боевик","драма"],              directors:["Тед Котчефф"],                       actors:["Сильвестр Сталлоне","Брайан Деннехи"],                                  img:"https://kinogo.ec/uploads/posts/2020-03/1585442933-1829798561.jpg" },
  { title:"Выживший",                       file:"The_Revenant.html",                          key:"The Revenant 2015",                     year:2015, country:"США",             genres:["драма","боевик"],              directors:["Алехандро Гонсалес Иньярриту"],     actors:["Леонардо ДиКаприо","Том Харди"],                                        img:"https://kinogo.online/uploads/posts/2021-02/1614528568-1065569495.jpg" },
  { title:"Апокалипсис по-голливудски",     file:"This_is_the_End.html",                       key:"This Is the End 2013",                  year:2013, country:"США",             genres:["комедия","ужасы"],             directors:["Сет Роген","Эван Голдберг"],         actors:["Джеймс Франко","Джона Хилл","Сет Роген"],                              img:"https://play-lh.googleusercontent.com/AoLjRe-KKJqd8ogN33AhIdbpQTOQFvaUDZjIkuf5v0LaPGdKv4N--FX97XkDpuWA4i9V" },
  { title:"Мост в Терабитию",               file:"Bridge_to_Terabithia.html",                  key:"Bridge to Terabithia 2007",             year:2007, country:"США",             genres:["драма","фэнтези","семейный"],  directors:["Габор Чупо"],                        actors:["Джош Хатчерсон","АннаСофия Робб"],                                      img:"https://mobb.kinovasek.men/uploads/posts/2025-03/67db17498a418.webp" },
  { title:"Банда Келли",                    file:"Ned_Kelly.html",                             key:"Ned Kelly 2003",                        year:2003, country:"Австралия",       genres:["драма","криминал","вестерн"],  directors:["Грегор Джордан"],                    actors:["Хит Леджер","Орландо Блум","Наоми Уоттс"],                             img:"https://kinogo.media/uploads/posts/2021-10/1634994106_iphone360_5572.jpg" },
  { title:"Хоббит: Нежданное путешествие",  file:"Hobbit.html",                                key:"The Hobbit 2012",                       year:2012, country:"Новая Зеландия",  genres:["фэнтези","приключения"],       directors:["Питер Джексон"],                     actors:["Мартин Фриман","Иэн МакКеллен","Ричард Армитидж"],                     img:"https://kinogo.online/uploads/posts/2021-02/1614408723-1574705447.jpg" },
  { title:"Ущелье",                         file:"Gorge.html",                                 key:"The Gorge 2025",                        year:2025, country:"США",             genres:["фантастика","мелодрама","боевик"],directors:["Скотт Дерриксон"],              actors:["Майлз Теллер","Аня Тейлор-Джой"],                                       img:"https://kinogo.online/uploads/posts/2025-02/1741618926-95a5cfd520_124112.jpg" },
  { title:"Криминальное чтиво",             file:"Pulp_fiction.html",                          key:"Pulp Fiction 1994",                     year:1994, country:"США",             genres:["криминал","триллер","драма"],  directors:["Квентин Тарантино"],                 actors:["Джон Траволта","Сэмюэл Л. Джексон","Ума Турман","Брюс Уиллис"],       img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFOc_nYJ6EvcrCVy6WQ-t5tTCtRvw12buu9Q&s" },
  { title:"Где моя тачка, чувак?",          file:"Dude_wheres_my_car.html",                    key:"Dude Wheres My Car 2000",               year:2000, country:"США",             genres:["комедия"],                     directors:["Дэнни Лейнер"],                      actors:["Эштон Катчер","Шон Уильям Скотт"],                                      img:"https://upload.wikimedia.org/wikipedia/ru/f/fe/Dude%2C_Where%27s_My_Car.jpg" },
  { title:"Джанго освобождённый",           file:"Django.html",                                key:"Django Unchained 2012",                 year:2012, country:"США",             genres:["вестерн","боевик","криминал"], directors:["Квентин Тарантино"],                 actors:["Джейми Фокс","Кристоф Вальц","Леонардо ДиКаприо"],                     img:"https://kinogo.online/uploads/posts/2021-02/1614410299-1099694772.jpg" },
  { title:"Карате-пацан",                   file:"Karate_kid.html",                            key:"The Karate Kid 2010",                   year:2010, country:"США / Китай",     genres:["драма","боевик","семейный"],   directors:["Харальд Цварт"],                     actors:["Джейден Смит","Джеки Чан"],                                             img:"https://kinogo.online/uploads/mini/shortstory-mob/492/1614458213-830135586.jpg" },
  { title:"Муви 43",                        file:"Movie_43.html",                              key:"Movie 43 2013",                         year:2013, country:"США",             genres:["комедия","пародия"],           directors:["Питер Фаррелли","Боб Оденкёрк"],    actors:["Хью Джекман","Кейт Уинслет","Хэлли Берри"],                            img:"https://mobb.kinovasek.men/uploads/posts/2025-03/67daf54f2f903.webp" },
  { title:"Последний киногерой",            file:"Last_action_hero.html",                      key:"Last Action Hero 1993",                 year:1993, country:"США",             genres:["боевик","комедия","фэнтези"],  directors:["Джон МакТирнан"],                    actors:["Арнольд Шварценеггер","Остин О'Брайен"],                                img:"https://www.kino-teatr.ru/movie/posters/big/4/3/17434.jpg" },
  { title:"Пол: Секретный материальчик",    file:"Paul.html",                                  key:"Paul 2011",                             year:2011, country:"Великобритания",  genres:["комедия","фантастика"],        directors:["Грег Моттола"],                      actors:["Саймон Пегг","Ник Фрост","Сет Роген"],                                 img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdZzyUs7VZPIKv66use17mojiKWYc6-SH98w&s" },
  { title:"Хэнкок",                         file:"Hancock.html",                               key:"Hancock 2008",                          year:2008, country:"США",             genres:["боевик","комедия","фантастика"],directors:["Питер Берг"],                       actors:["Уилл Смит","Шарлиз Терон","Джейсон Бейтман"],                          img:"https://kinogo.online/uploads/posts/2021-02/1614415093-1395068612.jpg" },
  { title:"Время",                          file:"In_Time.html",                               key:"in_time_2011",                          year:2011, country:"США",             genres:["фантастика","боевик","триллер"],directors:["Эндрю Никкол"],                    actors:["Джастин Тимберлейк","Аманда Сейфрид","Киллиан Мёрфи"],                 img:"https://kinogo.online/uploads/posts/2021-02/1614395730-1614395730.jpg" },
  { title:"Белые цыпочки",                  file:"White_Chicks.html",                          key:"white_chicks_2004",                     year:2004, country:"США",             genres:["комедия"],                     directors:["Киинан Айвори Уэйанс"],              actors:["Шон Уэйанс","Марлон Уэйанс","Терри Крюс"],                             img:"https://upload.wikimedia.org/wikipedia/ru/5/51/White_Chicks.jpg" },
  { title:"Бегущий в лабиринте",            file:"Maze_Runner.html",                           key:"maze_runner_2014",                      year:2014, country:"США",             genres:["фантастика","боевик","триллер"],directors:["Уэс Болл"],                        actors:["Дилан О'Брайен","Кая Скоделарио","Томас Броди-Сангстер"],              img:"https://kinogo.online/uploads/posts/2021-02/1614420018-1614420018.jpg" },
  { title:"Гладиатор",                      file:"Gladiator.html",                             key:"gladiator_2000",                        year:2000, country:"США",             genres:["боевик","история","драма"],    directors:["Ридли Скотт"],                       actors:["Рассел Кроу","Хоакин Феникс","Конни Нильсен"],                          img:"https://kinogo.online/uploads/posts/2021-02/1614441975-2608244.jpg" },
  { title:"Миллион способов потерять голову",file:"Million_Ways.html",                         key:"million_ways_2014",                     year:2014, country:"США",             genres:["комедия","вестерн"],           directors:["Сет МакФарлейн"],                    actors:["Сет МакФарлейн","Шарлиз Терон","Лиам Нисон","Аманда Сейфрид"],        img:"https://kinogo.online/uploads/posts/2021-02/1614510276-1614510276.jpg" },
  { title:"50 первых поцелуев",             file:"50_First_Dates.html",                        key:"50_first_dates_2004",                   year:2004, country:"США",             genres:["комедия","мелодрама"],         directors:["Питер Сигал"],                       actors:["Адам Сэндлер","Дрю Бэрримор","Роб Шнайдер"],                           img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkQmxUJWzAX-Jnp2vTDdO1RqJm5HgX5YN5Cw&s" },
  { title:"Семь",                           file:"Seven.html",                                 key:"seven_1995",                            year:1995, country:"США",             genres:["криминал","триллер","детектив"],directors:["Дэвид Финчер"],                    actors:["Брэд Питт","Морган Фриман","Кевин Спейси"],                             img:"https://kinogo.org/uploads/posts/2021-09/1694491844-sem.jpg" },
  { title:"Матрица",                        file:"Matrix.html",                                key:"matrix_1999",                           year:1999, country:"США",             genres:["фантастика","боевик","триллер"],directors:["Лана Вачовски","Лилли Вачовски"],  actors:["Киану Ривз","Лоренс Фишбёрн","Кэрри-Энн Мосс","Хьюго Уивинг"],       img:"https://kinogo.online/uploads/posts/2021-02/1614391860-1614391860.jpg" },
  { title:"Смешанные",                      file:"Blended.html",                               key:"blended_2014",                          year:2014, country:"США",             genres:["комедия","мелодрама"],         directors:["Фрэнк Корачи"],                      actors:["Адам Сэндлер","Дрю Бэрримор","Белла Торн"],                            img:"https://kinogo.online/uploads/posts/2021-02/1614438920-1614438920.jpg" },
  { title:"Папе снова 17",                  file:"17_Again.html",                              key:"17_again_2009",                         year:2009, country:"США",             genres:["комедия","фэнтези","драма"],   directors:["Бёрр Стирс"],                        actors:["Зак Эфрон","Мэттью Перри","Лесли Манн"],                               img:"https://kinogo.online/uploads/posts/2021-02/1614427008-1614427008.jpg" },
  { title:"Супер перцы",                    file:"Superbad.html",                              key:"superbad_2007",                         year:2007, country:"США",             genres:["комедия"],                     directors:["Грег Моттола"],                      actors:["Джона Хилл","Майкл Сера","Кристофер Минц-Пласс"],                      img:"https://m.media-amazon.com/images/M/MV5BY2IyNTE0NjYtNjNjMS00Zjk4LWI3YjktYzU1NTYxNzM0OTdiXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg" },
  { title:"Поймай меня если сможешь",       file:"Catch_Me_If_You_Can.html",                   key:"catch_me_if_you_can_2002",              year:2002, country:"США",             genres:["криминал","биография","драма"], directors:["Стивен Спилберг"],                  actors:["Леонардо ДиКаприо","Том Хэнкс","Кристофер Уокен"],                    img:"https://kinogo.online/uploads/posts/2021-02/1614393240-1614393240.jpg" },
  { title:"Солдаты неудачи",                file:"Tropic_Thunder.html",                        key:"tropic_thunder_2008",                   year:2008, country:"США",             genres:["комедия","боевик","пародия"],  directors:["Бен Стиллер"],                       actors:["Бен Стиллер","Джек Блэк","Роберт Дауни Мл."],                          img:"https://kinogo.online/uploads/posts/2021-02/1614436228-1614436228.jpg" },
  { title:"Зелёная миля",                   file:"Green_Mile.html",                            key:"green_mile_1999",                       year:1999, country:"США",             genres:["драма","фэнтези","криминал"],  directors:["Фрэнк Дарабонт"],                    actors:["Том Хэнкс","Майкл Кларк Дункан","Дэвид Морс"],                         img:"https://kinogo.ec/uploads/posts/2020-03/1585530011-1127491609.jpg" },
  // ═══════════════════════════════════════════════════════
  //  НОВЫЕ ФИЛЬМЫ
  // ═══════════════════════════════════════════════════════
  { title:"Шалун",                         file:"Little_Man.html",                    key:"little_man_2006",               year:2006, country:"США",            genres:["комедия","криминал"],               directors:["Кинан Айвори Уэйанс"],                    actors:["Марлон Уэйанс","Шон Уэйанс"],                                        img:"https://image.tmdb.org/t/p/w500/fNZW4gMLymN5SflFT8wQvfYvnGr.jpg" },
  { title:"Лысый нянька: Спецзадание",     file:"The_Pacifier.html",                  key:"the_pacifier_2005",             year:2005, country:"США",            genres:["комедия","боевик","семейный"],      directors:["Адам Шэнкман"],                           actors:["Вин Дизель","Лорен Грэм"],                                            img:"https://image.tmdb.org/t/p/w500/5iu9TqnhNELEZ0QbvDUxBDhlqS5.jpg" },
  { title:"Папа-досвидос",                 file:"Thats_My_Boy.html",                  key:"thats_my_boy_2012",             year:2012, country:"США",            genres:["комедия"],                          directors:["Шон Андерс"],                             actors:["Адам Сэндлер","Энди Сэмберг"],                                        img:"https://image.tmdb.org/t/p/w500/pq4P1MZZhDTe1xRYlQTDxrHT0Eh.jpg" },
  { title:"Тронутые",                      file:"Road_Within.html",                   key:"road_within_2014",              year:2014, country:"США",            genres:["комедия","драма","приключения"],    directors:["Грен Уэллс"],                             actors:["Роберт Шиэн","Дев Патель","Зои Кравиц"],                              img:"https://image.tmdb.org/t/p/w500/p3QiGzGsK2tq2mRGkzLFNf2nE9G.jpg" },
  { title:"На Западном фронте без перемен",file:"All_Quiet_on_the_Western_Front.html",key:"all_quiet_2022",                year:2022, country:"Германия",       genres:["драма","военный"],                  directors:["Эдвард Бергер"],                          actors:["Феликс Каммерер","Альбрехт Шух","Даниэль Брюль"],                     img:"https://image.tmdb.org/t/p/w500/hgRMSOt7a1b8qyQR68vUixJPang.jpg" },
  { title:"Мальчишник в Вегасе",           file:"The_Hangover.html",                  key:"hangover_2009",                 year:2009, country:"США",            genres:["комедия","криминал"],               directors:["Тодд Филлипс"],                           actors:["Брэдли Купер","Зак Галифианакис","Эд Хелмс"],                         img:"https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggkn.jpg" },
  { title:"Любовь зла",                    file:"Love_Is_Evil.html",                  key:"love_is_evil_1999",             year:1999, country:"США",            genres:["комедия","мелодрама"],              directors:["Джефф Фрэнклин"],                         actors:["Фрэнч Стюарт","Бриджит Уилсон"],                                      img:"https://image.tmdb.org/t/p/w500/cYqxn6VqMCBbpJEkxZ8Gvpz4oWX.jpg" },
  { title:"Кровавый алмаз",                file:"Blood_Diamond.html",                 key:"blood_diamond_2006",            year:2006, country:"США",            genres:["триллер","драма","приключения"],    directors:["Эдвард Цвик"],                            actors:["Леонардо ДиКаприо","Дживон Хоузу","Дженнифер Коннелли"],              img:"https://image.tmdb.org/t/p/w500/6oKVF1tWPDUKyoFMdcXBpJRiFnI.jpg" },
  { title:"Притворись моей женой",         file:"Just_Go_With_It.html",               key:"just_go_with_it_2011",          year:2011, country:"США",            genres:["комедия","мелодрама"],              directors:["Деннис Дуган"],                           actors:["Адам Сэндлер","Дженнифер Энистон","Бруклин Декер"],                   img:"https://image.tmdb.org/t/p/w500/9BW3HFUFd5y8dkXGXBFfpxsYF8W.jpg" },
  { title:"Впритык",                       file:"Due_Date.html",                      key:"due_date_2010",                 year:2010, country:"США",            genres:["комедия"],                          directors:["Тодд Филлипс"],                           actors:["Роберт Дауни-мл.","Зак Галифианакис"],                                img:"https://image.tmdb.org/t/p/w500/4kJJ2lAFlqXMVQHVSF2DkMYsOfN.jpg" },
  { title:"Телохранитель киллера",         file:"Hitmans_Bodyguard.html",             key:"hitmans_bodyguard_2017",        year:2017, country:"США",            genres:["комедия","боевик","криминал"],      directors:["Патрик Хьюз"],                            actors:["Райан Рейнольдс","Сэмюэл Л. Джексон","Салма Хайек"],                  img:"https://image.tmdb.org/t/p/w500/nPGtMSqkYnChfCfLMSvZofyGR3.jpg" },
  { title:"Типа крутые легавые",           file:"Hot_Fuzz.html",                      key:"hot_fuzz_2007",                 year:2007, country:"Великобритания", genres:["комедия","боевик","детектив"],      directors:["Эдгар Райт"],                             actors:["Саймон Пегг","Ник Фрост","Тимоти Далтон"],                            img:"https://image.tmdb.org/t/p/w500/tID2wR9vHQo94vIlDxWXnJcQ0jO.jpg" },
  { title:"Типа копы",                     file:"Lets_Be_Cops.html",                  key:"lets_be_cops_2014",             year:2014, country:"США",            genres:["комедия","боевик","криминал"],      directors:["Люк Гринфилд"],                           actors:["Дэймон Уэйанс-мл.","Джейк Джонсон"],                                  img:"https://image.tmdb.org/t/p/w500/ry1eFDpFDKHGXM5zFNYjHF3S2Bh.jpg" },
  { title:"Третий лишний",                 file:"Ted.html",                           key:"ted_2012",                      year:2012, country:"США",            genres:["комедия","фэнтези"],                directors:["Сет Макфарлейн"],                         actors:["Марк Уолберг","Мила Кунис","Сет Макфарлейн"],                         img:"https://image.tmdb.org/t/p/w500/v1yOoCLPcfj3KR0E60m0jXY4j4V.jpg" },
  { title:"Ночь в музее",                  file:"Night_at_the_Museum.html",           key:"night_at_museum_2006",          year:2006, country:"США",            genres:["комедия","приключения","фэнтези"], directors:["Шон Леви"],                               actors:["Бен Стиллер","Карла Гуджино","Дик Ван Дайк"],                         img:"https://image.tmdb.org/t/p/w500/uItKWHMKRzBqVbWpvBQqnHxfxVT.jpg" },
  { title:"Эйс Вентура",                   file:"Ace_Ventura.html",                   key:"ace_ventura_1994",              year:1994, country:"США",            genres:["комедия","детектив"],               directors:["Том Шедьяк"],                             actors:["Джим Керри","Кортни Кокс","Шон Янг"],                                 img:"https://image.tmdb.org/t/p/w500/y9rTp4zJhfOsJPZq2Y6KT2wHGlk.jpg" },
  { title:"Американский пирог",            file:"American_Pie.html",                  key:"american_pie_1999",             year:1999, country:"США",            genres:["комедия","мелодрама"],              directors:["Пол Вайц"],                               actors:["Джейсон Биггс","Шон Уильям Скотт","Алисон Ханниган"],                 img:"https://image.tmdb.org/t/p/w500/bMHLm5nvFlLmfXNmLqN1aTMnkL9.jpg" },
  { title:"Брюс всемогущий",               file:"Bruce_Almighty.html",                key:"bruce_almighty_2003",           year:2003, country:"США",            genres:["комедия","фэнтези"],                directors:["Том Шедьяк"],                             actors:["Джим Керри","Морган Фримен","Дженнифер Энистон"],                     img:"https://image.tmdb.org/t/p/w500/qYgHpEqX6XTJHE9mWDI7DZNI7oY.jpg" },
  { title:"Большой Стэн",                  file:"Big_Stan.html",                      key:"big_stan_2007",                 year:2007, country:"США",            genres:["комедия","боевик"],                 directors:["Роб Шнайдер"],                            actors:["Роб Шнайдер","Дэвид Кэррэдайн"],                                      img:"https://image.tmdb.org/t/p/w500/uGq7pHEiJXABPg7BsBzXwTa4H5b.jpg" },
  { title:"Поймай толстуху, если сможешь", file:"Identity_Thief.html",                key:"identity_thief_2013",           year:2013, country:"США",            genres:["комедия","криминал"],               directors:["Сет Гордон"],                             actors:["Джейсон Бейтман","Мелисса Маккарти"],                                 img:"https://image.tmdb.org/t/p/w500/8qlFAJHxs0JhR0JOF1PLZPAH0ZZ.jpg" },
  { title:"Каникулы",                      file:"Vacation.html",                      key:"vacation_2015",                 year:2015, country:"США",            genres:["комедия","приключения"],            directors:["Джон Фрэнсис Дэйли","Джонатан Голдштейн"],actors:["Эд Хелмс","Кристина Эпплгейт","Крис Хемсворт"],                       img:"https://image.tmdb.org/t/p/w500/glGjp6Nbi6F3Q1gnJMMoHBSUxcq.jpg" },
  { title:"2012",                          file:"2012.html",                          key:"movie_2012",                    year:2009, country:"США",            genres:["фантастика","боевик","катастрофа"], directors:["Роланд Эммерих"],                         actors:["Джон Кьюсак","Аманда Пит","Чиветель Эджиофор"],                       img:"https://image.tmdb.org/t/p/w500/1s5yY94TFBRlUBfWMvSxrGAhQp7.jpg" },
  { title:"План побега",                   file:"Escape_Plan.html",                   key:"escape_plan_2013",              year:2013, country:"США",            genres:["боевик","триллер","криминал"],      directors:["Микаэль Хофстрём"],                       actors:["Сильвестр Сталлоне","Арнольд Шварценеггер"],                          img:"https://image.tmdb.org/t/p/w500/lAzC6JOnBXpBbbHXgCdODEPOFHl.jpg" },
  { title:"Джуманджи: Зов джунглей",      file:"Jumanji_2017.html",                  key:"jumanji_2017",                  year:2017, country:"США",            genres:["комедия","приключения","фантастика"],directors:["Джейк Кэздан"],                          actors:["Двейн Джонсон","Джек Блэк","Кевин Харт","Карен Гиллан"],             img:"https://image.tmdb.org/t/p/w500/bXrZ5iHBEjH7WMidbUDQ0U2xbmr.jpg" },
  { title:"Начало",                        file:"Inception.html",                     key:"inception_2010",                year:2010, country:"США",            genres:["фантастика","триллер","боевик"],    directors:["Кристофер Нолан"],                        actors:["Леонардо ДиКаприо","Джозеф Гордон-Левитт","Эллиот Пейдж"],            img:"https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg" },
  { title:"Волк с Уолл-стрит",            file:"Wolf_of_Wall_Street.html",           key:"wolf_of_wall_street_2013",      year:2013, country:"США",            genres:["драма","комедия","криминал","биография"],directors:["Мартин Скорсезе"],                   actors:["Леонардо ДиКаприо","Джона Хилл","Марго Робби"],                       img:"https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg" },
  { title:"Однажды в… Голливуде",         file:"Once_Upon_Time_in_Hollywood.html",    key:"once_upon_time_hollywood_2019", year:2019, country:"США",            genres:["драма","комедия"],                  directors:["Квентин Тарантино"],                      actors:["Леонардо ДиКаприо","Брэд Питт","Марго Робби"],                        img:"https://image.tmdb.org/t/p/w500/8j58iEBbyxQNcsn9imHiS3LmWnj.jpg" },
  { title:"Один дома",                    file:"Home_Alone.html",                     key:"home_alone_1990",               year:1990, country:"США",            genres:["комедия","семейный"],               directors:["Крис Коламбус"],                          actors:["Маколей Калкин","Джо Пеши","Дэниел Стерн"],                           img:"https://image.tmdb.org/t/p/w500/4LnSKEKpVh8pEABWfBQ4OvTiMTD.jpg" },
  { title:"Дивергент",                    file:"Divergent.html",                      key:"divergent_2014",                year:2014, country:"США",            genres:["фантастика","приключения","боевик"],directors:["Нил Бёрджер"],                           actors:["Шейлин Вудли","Тео Джеймс","Кейт Уинслет"],                          img:"https://image.tmdb.org/t/p/w500/Aw5MCiAIHnTlcDfbFmr3IrX7YAK.jpg" },
  { title:"Человек дождя",                file:"Rain_Man.html",                       key:"rain_man_1988",                 year:1988, country:"США",            genres:["драма","мелодрама"],                directors:["Барри Левинсон"],                         actors:["Дастин Хоффман","Том Круз","Валерия Голино"],                         img:"https://image.tmdb.org/t/p/w500/zaSQXlFEbBdGhASrCrFhFdTDm4Y.jpg" },
  { title:"Терминал",                     file:"The_Terminal.html",                   key:"the_terminal_2004",             year:2004, country:"США",            genres:["комедия","драма","мелодрама"],      directors:["Стивен Спилберг"],                        actors:["Том Хэнкс","Кэтрин Зета-Джонс","Стэнли Туччи"],                      img:"https://image.tmdb.org/t/p/w500/bBNdI2kfKOVWPHx0S50RjnFVMuH.jpg" },
  { title:"Диктатор",                     file:"The_Dictator.html",                   key:"the_dictator_2012",             year:2012, country:"США",            genres:["комедия"],                          directors:["Ларри Чарльз"],                           actors:["Саша Барон Коэн","Анна Фарис","Бен Кингсли"],                         img:"https://image.tmdb.org/t/p/w500/0AFAQHDSCdFfXN2vGYjGBiIE64F.jpg" },
  { title:"Всегда говори «Да»",           file:"Yes_Man.html",                        key:"yes_man_2008",                  year:2008, country:"США",            genres:["комедия","мелодрама"],              directors:["Пейтон Рид"],                             actors:["Джим Керри","Зои Дешанель","Брэдли Купер"],                           img:"https://image.tmdb.org/t/p/w500/4EM8jJTX3yjCMwF7PU8BrHl0XQH.jpg" },
  { title:"Пипец",                        file:"Kick_Ass.html",                       key:"kickass_2010",                  year:2010, country:"США",            genres:["комедия","боевик","криминал"],      directors:["Мэттью Вон"],                             actors:["Аарон Тейлор-Джонсон","Хлоя Грейс Морец","Николас Кейдж"],          img:"https://image.tmdb.org/t/p/w500/lxi3OM3kBXHEL1c5lrBkfQi4v7.jpg" },
  { title:"Копы в глубоком запасе",       file:"Other_Guys.html",                     key:"other_guys_2010",               year:2010, country:"США",            genres:["комедия","боевик","криминал"],      directors:["Адам МакКей"],                            actors:["Уилл Феррелл","Марк Уолберг","Ева Мендес"],                          img:"https://image.tmdb.org/t/p/w500/2lXH1WrL8dJbGm3T7K28AiWjPX1.jpg" },
  { title:"Агент Джонни Инглиш",          file:"Johnny_English.html",                 key:"johnny_english_2003",           year:2003, country:"Великобритания", genres:["комедия","боевик","шпионаж"],       directors:["Питер Хоар"],                             actors:["Роуэн Аткинсон","Натали Имбрулья","Бен Миллер"],                     img:"https://image.tmdb.org/t/p/w500/1v6cCpBHy2eCrJCEiOtH5Qixzxv.jpg" },
  { title:"Большая мамочка",              file:"Big_Mommas_House.html",               key:"big_mommas_house_2000",         year:2000, country:"США",            genres:["комедия","боевик","криминал"],      directors:["Раджа Госнелл"],                          actors:["Мартин Лоуренс","Нии Лонг","Пол Джиамати"],                          img:"https://image.tmdb.org/t/p/w500/jTWFQH3RXTk4cpTJWmFt9Qhj7mN.jpg" },
];

// ═══════════════════════════════════════════════════════
//  СЕРИИ / ПРОДОЛЖЕНИЯ
// ═══════════════════════════════════════════════════════
const SERIES_GROUPS = [
  ["Per un pugno di dollari", "For a Few Dollars More", "good-bad-ugly"],
  ["Captain America The First Avenger"],
  ["The Hunger Games", "maze_runner_2014", "in_time_2011"],
  ["Zombieland"],
  ["Scary Movie 2000"],
  ["Police Academy 1984"],
  ["Bad Boys"],
  ["Rocky 1976", "Rambo First Blood 1982"],
  ["Blade"],
  ["Final Destination"],
  ["Harold & Kumar Go to White Castle"],
  ["Star Trek 2009"],
  ["The Hobbit 2012"],
  ["The Equalizer"],
  ["hangover_2009"],
  ["jumanji_2017"],
  ["american_pie_1999"],
  ["inception_2010"],
  ["kickass_2010"],
  ["wolf_of_wall_street_2013", "once_upon_time_hollywood_2019"],
  ["home_alone_1990"],
  ["rain_man_1988"],
  ["the_terminal_2004"],
  ["ace_ventura_1994"],
  ["hot_fuzz_2007"],
  ["escape_plan_2013"],
  ["all_quiet_2022"],
  ["the_pacifier_2005"],
  ["thats_my_boy_2012"],
  ["little_man_2006"],
  ["ted_2012"],
];

// ═══════════════════════════════════════════════════════
//  УМНЫЙ АЛГОРИТМ РЕКОМЕНДАЦИЙ
// ═══════════════════════════════════════════════════════
function getSmartRecs(currentKey, count = 4) {
  const current = FISH_MOVIES.find(m => m.key === currentKey);
  if (!current) return [];

  const others = FISH_MOVIES.filter(m => m.key !== currentKey);
  const scored = others.map(m => {
    let score = 0;
    let badge = "similar";
    let badgeText = "Похожее";

    const currentSeries = SERIES_GROUPS.find(g => g.includes(currentKey));
    if (currentSeries && currentSeries.includes(m.key)) {
      score += 100;
      badge = "sequel";
      badgeText = "Из серии";
    }

    const currentMainActors = current.actors.slice(0, 2);
    const matchActors = m.actors.filter(a => currentMainActors.includes(a));
    if (matchActors.length > 0) {
      score += 40 * matchActors.length;
      if (score < 100) { badge = "actor"; badgeText = matchActors[0]; }
    }

    const matchDir = m.directors.filter(d => current.directors.includes(d));
    if (matchDir.length > 0) {
      score += 30;
      if (score < 40) { badge = "director"; badgeText = "Тот же режиссёр"; }
    }

    const matchGenres = m.genres.filter(g => current.genres.includes(g));
    score += matchGenres.length * 10;

    if (Math.abs(m.year - current.year) <= 5) score += 5;

    return { ...m, score, badge, badgeText };
  });

  return scored
    .sort((a, b) => b.score - a.score)
    .slice(0, count);
}

// ═══════════════════════════════════════════════════════
//  РЕНДЕР РЕКОМЕНДАЦИЙ В HTML
// ═══════════════════════════════════════════════════════
function renderSmartRecs(currentKey, containerId = "smartRecs") {
  const container = document.getElementById(containerId);
  if (!container) return;

  const recs = getSmartRecs(currentKey);
  if (!recs.length) { container.innerHTML = ""; return; }

  const badgeColors = {
    sequel:   "background:linear-gradient(135deg,#7a3a00,#c06010);color:#fff;box-shadow:0 0 10px rgba(200,90,0,0.6)",
    actor:    "background:linear-gradient(135deg,#1a3a6a,#2060b0);color:#fff",
    director: "background:linear-gradient(135deg,#3a1a6a,#6030a0);color:#fff",
    similar:  "background:rgba(30,24,14,0.88);border:1px solid var(--gold-dim);color:var(--gold)",
  };

  container.innerHTML = recs.map((m, i) => `
    <a href="${m.file}" class="rec-card" style="animation-delay:${i * 0.07}s">
      <div class="rec-card-inner">
        <img src="${m.img}" alt="${m.title}" loading="lazy">
        <div class="rec-card-overlay">
          <div class="rec-card-overlay-title">${m.title}</div>
          <div class="rec-card-overlay-meta">${m.country} · ${m.year} · ${m.genres[0]}</div>
        </div>
        <span class="rec-badge" style="${badgeColors[m.badge] || badgeColors.similar}">${m.badgeText}</span>
      </div>
      <div class="rec-card-title">${m.title}</div>
      <div class="rec-card-year">${m.year}</div>
    </a>
  `).join("");
}
